# Generated by Django 2.2 on 2019-09-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author_name', models.CharField(max_length=200, verbose_name='Имя Автора')),
                ('text', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date', models.DateField(blank=True, max_length=3000, null=True, verbose_name='Дата')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('change_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата_изменения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20, verbose_name='Тема')),
            ],
        ),
    ]
